language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
#  - jruby-19mode # JRuby in 1.9 mode -> Problems with bigint
  - rbx

script:
  bundle exec rake

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev
  - gem update && gem install bundler